# Check that the version in the frontend/package.json file is the same as the backend/swagger.yaml version
# If they are not the same, fail the build

name: Version equal check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check that the version in the frontend/package.json file is the same as the backend/swagger.yaml version
        run: |
          cd frontend
          FRONTEND_VERSION=$(cat package.json | grep version | cut -d '"' -f 4)
          cd ../backend
          BACKEND_VERSION=$(cat swagger.yaml | grep version | cut -d ':' -f 2 | sed 's/ //g')
          if [ "$FRONTEND_VERSION" != "$BACKEND_VERSION" ]; then
            echo "Version mismatch: frontend/package.json version $FRONTEND_VERSION != backend/swagger.yaml version $BACKEND_VERSION"
            exit 1
          fi
